import chalk from 'chalk';
import path from 'node:path';
import fse from 'fs-extra';
import type { AIAssistant, WorkspaceContext } from '../types.js';
import { generateClaudeConfig } from './claude.js';
import { generateAntigravityConfig } from './antigravity.js';
import { generateCodexConfig } from './codex.js';
import { generateCopilotConfig } from './copilot.js';
import { generateCursorConfig } from './cursor.js';
import { buildContextContent } from './base.js';
import { generateImplementationPlan } from './plan-generator.js';
import { generateSkills } from './skills-generator.js';
import { readWorkspaceFile, writeWorkspaceFile, workspaceFileExists, baseFileExists } from '../core/storage.js';
import {
  captureGenerationSnapshot,
  GENERATED_SNAPSHOT_HEADER,
  GENERATED_VIEW_HEADER,
  writeGenerationLock,
} from '../core/generation-lock.js';
import { commitWorkspaceArtifacts } from '../core/workspace-git.js';
import { getActiveStorageProvider } from '../core/adapters/registry.js';

/** Maps each assistant to its generator function and the file it produces. */
const GENERATORS: Record<
  AIAssistant,
  {
    generate: (ctx: WorkspaceContext, workspacePath: string) => Promise<void>;
    outputFile: string;
  }
> = {
  claude: { generate: generateClaudeConfig, outputFile: 'CLAUDE.md' },
  antigravity: { generate: generateAntigravityConfig, outputFile: 'AGENTS.md' },
  codex: { generate: generateCodexConfig, outputFile: 'AGENTS.md' },
  copilot: { generate: generateCopilotConfig, outputFile: '.github/copilot-instructions.md' },
  cursor: { generate: generateCursorConfig, outputFile: '.cursor/rules/nexusflow.mdc' },
};

/**
 * A short human index of the workspace. Deliberately not the full assistant
 * context: that lives in `AGENTS.md`, and a second copy would only be a file to
 * keep in sync.
 */
function buildWorkspaceIndex(ctx: WorkspaceContext): string {
  const { feature } = ctx;
  const repos = ctx.repos.map((repo) => `- \`${repo.name}\` — ${repo.path}`).join('\n');

  return `# Workspace: ${feature.id}

${feature.description}

> Assistant context lives in **AGENTS.md**. Most agent tools read that file
> directly; Claude Code reads \`CLAUDE.md\`, which imports it. This file is just
> an index for people.

## Repositories

${repos || '_None._'}

## Files in this workspace

| File | What it holds |
|---|---|
| \`AGENTS.md\` | The context your assistant loads: projects, relationships, verification commands |
| \`CLAUDE.md\` | A one-line \`@AGENTS.md\` import, plus anything Claude-specific |
| \`nexusflow-knowledge.md\` | Accumulated decisions and gotchas, one per \`###\` heading. Search it; do not read it whole |
| \`nexusflow-plan.md\` | Dependency-ordered implementation phases |

## Useful commands

\`\`\`
nexusflow status      # what changed, across every repo
nexusflow diff        # the actual changes
nexusflow refresh     # regenerate these files
nexusflow doctor      # check the workspace is healthy
\`\`\`

_Generated by NexusFlow. Run \`nexusflow refresh\` to update._
`;
}

function buildKnowledgeContent(ctx: WorkspaceContext): string {
  const { feature } = ctx;

  // The four accumulating sections — Project Assumptions, Clarifying Questions,
  // Architecture Decisions, Known Gotchas — are deliberately absent from a fresh
  // file. They used to ship as headings over `_(No X recorded yet.)_`, which two
  // independent evaluating agents both reported as "100% unfilled template
  // placeholders, zero actual content" while this file is linked from the
  // generated context. `insertUnderHeading` appends a missing section at
  // end-of-file (see core/knowledge.ts), so `nexusflow knowledge add` creates
  // each one the moment it has something to put there.
  return `# Workspace Knowledge — ${feature.id}

> Accumulated decisions and gotchas for this feature. Append with
> \`nexusflow knowledge add -t decision|gotcha --title "..." -m "..."\`, which creates the
> section it needs.

## Feature Goal

${feature.description}

`;
}

/** Remove only NexusFlow's old unchecked template rows; authored progress survives. */
export function removeGeneratedProgressChecklist(content: string, repoNames: string[]): string {
  const eol = content.includes('\r\n') ? '\r\n' : '\n';
  const generated = new Set(repoNames.map((name) => `- [ ] ${name} — changes implemented and tested`));
  const lines = content.split(/\r?\n/);
  const heading = lines.findIndex((line) => /^##\s+Implementation Progress\s*$/.test(line));
  if (heading < 0) return content;
  let end = lines.length;
  for (let i = heading + 1; i < lines.length; i++) {
    if (/^#{1,2}\s/.test(lines[i]!)) { end = i; break; }
  }
  const body = lines.slice(heading + 1, end).filter((line) => !generated.has(line.trim()));
  if (body.every((line) => !line.trim())) {
    const before = lines.slice(0, heading);
    while (before.at(-1)?.trim() === '') before.pop();
    const after = lines.slice(end);
    while (after[0]?.trim() === '') after.shift();
    return [...before, ...(before.length && after.length ? [''] : []), ...after].join(eol).replace(/\s+$/, '') + eol;
  }
  return [...lines.slice(0, heading + 1), ...body, ...lines.slice(end)].join(eol);
}

/**
 * Builds the base codebase knowledge starter content.
 *
 * Exported so the knowledge engine (`core/knowledge.ts`) can bootstrap a
 * missing base-knowledge file with the same section layout the generators use.
 */
export function buildBaseKnowledgeContent(repoName: string): string {
  return `# Base Codebase Knowledge — ${repoName}

> **This is a persistent cross-session memory file for ${repoName}.**
> AI assistants should read this at the start of each session, and append new architectural learnings, conventions, decisions, and gotchas at the end.
> This file persists across all features and tasks for this repository.

## Architecture & Domain Concepts
<!-- Document major design patterns, domain layers, and system concepts here. -->
- None recorded yet.

## Coding Conventions & Invariants
<!-- Document coding styles, library rules, and invariants that must not be broken. -->
- None recorded yet.

## Discovered Gotchas & Watch-outs
<!-- Document weird behaviors, workarounds, or bugs to avoid repeating them. -->
- None recorded yet.

## Architecture Decisions
<!-- Document key architectural decisions made for this repository over time. -->
- None recorded yet.
`;
}

/**
 * Generates AI context files for each of the selected assistants.
 *
 * Also generates:
 * - WORKSPACE.md — a short index for people, not an assistant-facing file
 * - nexusflow-knowledge.md — accumulated decisions and gotchas, if absent
 * - nexusflow-plan.md — implementation order based on dependency analysis
 *
 * Every file it writes describes the whole workspace, so there is no per-repo or
 * base-only subset to generate. The `onlyRepo` and `onlyBase` parameters are
 * gone with the per-repo architecture maps that were the only thing they scoped:
 * once the maps went, `onlyBase` made this function write nothing while its
 * caller still reported success, and `onlyRepo` narrowed a logging loop while
 * every generated file was rewritten in full.
 *
 * @param ctx           - The workspace context (feature + repos).
 * @param assistants    - Which AI assistants to generate context files for.
 * @param workspacePath - Absolute path to the workspace root directory.
 */
export async function generateContextFiles(
  ctx: WorkspaceContext,
  assistants: AIAssistant[],
  workspacePath: string,
): Promise<void> {
  const generation = await captureGenerationSnapshot(ctx.repos);
  const renderCtx: WorkspaceContext = { ...ctx, generation };
  const generatedOutputs: Array<{
    path: string;
    source: string;
    location: 'workspace' | 'local';
  }> = [];

  const canonical = `${GENERATED_SNAPSHOT_HEADER}\n\n${await buildContextContent(renderCtx)}`;
  await writeWorkspaceFile(workspacePath, ctx.feature.id, 'AGENTS.md', canonical);
  generatedOutputs.push({ path: 'AGENTS.md', source: 'workspace snapshot', location: 'workspace' });

  // WORKSPACE.md is a human-facing index, not an auto-loaded context file: no
  // assistant reads it by convention, so it used to be a byte-for-byte third
  // copy of CLAUDE.md and AGENTS.md. A pointer costs nothing and removes two
  // files that had to be kept in sync. The assistant-specific filenames still
  // carry the full content, because those ARE auto-loaded — turning one of
  // those into a pointer would trade free context for a tool call.
  try {
    await writeWorkspaceFile(workspacePath, ctx.feature.id, 'WORKSPACE.md', `${GENERATED_VIEW_HEADER}\n\n${buildWorkspaceIndex(renderCtx)}`);
    generatedOutputs.push({ path: 'WORKSPACE.md', source: 'AGENTS.md', location: 'workspace' });
    console.log(
      chalk.green('  ✔'),
      `Generated ${chalk.bold('WORKSPACE.md')} (human index)`,
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(
      chalk.red('  ✖'),
      `Failed to generate WORKSPACE.md: ${message}`,
    );
    throw error;
  }

  // Base knowledge is never pre-created: the starter was four headings over four
  // `- None recorded yet.` lines. `nexusflow knowledge add` bootstraps the file
  // with that layout on first write (see `insertIntoBase` in core/knowledge.ts),
  // so it appears once it has content, and an existing one is left untouched.

  {
    try {
      // Generate nexusflow-knowledge.md if it does not exist
      const knowledgeExists = await workspaceFileExists(workspacePath, ctx.feature.id, 'nexusflow-knowledge.md');
      if (!knowledgeExists) {
        const knowledgeContent = buildKnowledgeContent(renderCtx);
        await writeWorkspaceFile(workspacePath, ctx.feature.id, 'nexusflow-knowledge.md', knowledgeContent);
        console.log(chalk.green('  ✔'), `Generated ${chalk.bold('nexusflow-knowledge.md')} (persistent AI memory)`);
      } else {
        const existing = await readWorkspaceFile(workspacePath, ctx.feature.id, 'nexusflow-knowledge.md');
        const migrated = removeGeneratedProgressChecklist(existing, ctx.repos.map((repo) => repo.name));
        if (migrated !== existing) {
          await writeWorkspaceFile(workspacePath, ctx.feature.id, 'nexusflow-knowledge.md', migrated);
          console.log(chalk.green('  ✔'), 'Removed obsolete generated progress checklist');
        } else {
          console.log(chalk.gray('  ○'), `nexusflow-knowledge.md already exists — preserving existing content`);
        }
      }

      // No branch-diff file. It was `git diff --name-only` rewritten as a
      // bullet list, with every entry expanded to an absolute file:/// URL —
      // which tripled its size for no added fact. An assistant gets the same
      // answer, current rather than as-of-last-refresh, from one git call.
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(
        chalk.red('  ✖'),
        `Failed to generate workspace context files: ${message}`,
      );
      throw error;
    }
  }

  // No per-repo architecture map.
  //
  // Every line it emitted came from the repo's package.json — the manifest paths,
  // the test frameworks, `npm test`, `npm run dev` — so an assistant that opens
  // that file, which it does anyway, already knew all of it. Two independent
  // evaluating agents said as much: the maps added nothing beyond the manifest.
  // Worse, it was the first entry in the generated "Where to look" list, so the
  // agent was sent to read derived facts before starting work.
  //
  // The rule this settles: generate only what an agent cannot grep.

  // Generate configuration for each selected assistant
  for (const assistant of assistants) {
    if (assistant === 'codex' || assistant === 'antigravity') continue;
    const entry = GENERATORS[assistant];

    try {
      await entry.generate(renderCtx, workspacePath);
      generatedOutputs.push({ path: entry.outputFile, source: 'AGENTS.md', location: 'workspace' });
      console.log(
        chalk.green('  ✔'),
        `Generated ${chalk.bold(entry.outputFile)} for ${assistant}`,
      );
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(
        chalk.red('  ✖'),
        `Failed to generate ${entry.outputFile} for ${assistant}: ${message}`,
      );
      throw error;
    }
  }

  // AGENTS.md is the canonical context file: it is the cross-tool convention, so
  // Codex, Cursor, Devin and the rest read it directly. Claude Code is the
  // exception — it reads CLAUDE.md — which is why `claude.ts` writes a CLAUDE.md
  // that `@`-imports this one. That import is expanded at launch, so Claude gets
  // the whole body without a second copy existing anywhere.
  //
  // Written unconditionally, because the file is the source of truth rather than
  // a per-assistant artifact. When antigravity or codex is selected, its own
  // generator has already written the same content here.
  // Generate implementation plan from dependency analysis (if analysis data available)
  try {
    await generateImplementationPlan(renderCtx, workspacePath);
    generatedOutputs.push({ path: 'nexusflow-plan.md', source: 'workspace snapshot', location: 'workspace' });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(
      chalk.red('  ✖'),
      `Failed to generate implementation plan: ${message}`,
    );
    throw error;
  }

  // Resource materialization is transactional and owns assistant-discovered
  // files. Propagate failures so callers never report a partially applied
  // workspace as successful.
  await generateSkills(renderCtx, assistants, workspacePath);

  try {
    const resourceLock = await fse.readJson(path.join(workspacePath, '.nexusflow', 'resources.lock.json')) as {
      outputs?: Array<{ path: string }>;
    };
    generatedOutputs.push({ path: '.nexusflow/resources.lock.json', source: 'workspace resource selection', location: 'local' });
    for (const output of resourceLock.outputs ?? []) {
      generatedOutputs.push({ path: output.path, source: 'skill or agent catalog', location: 'local' });
    }
  } catch {
    // Resource materialization always writes this lock; its absence is a failed generation.
    throw new Error('Resource materialization completed without .nexusflow/resources.lock.json.');
  }

  await writeGenerationLock(workspacePath, generation, generatedOutputs);
  if (getActiveStorageProvider().meta.name === 'local') {
    await commitWorkspaceArtifacts(workspacePath, 'chore(nexusflow): refresh workspace artifacts');
  }
}

// Re-export individual generators for direct use
export { generateClaudeConfig } from './claude.js';
export { generateAntigravityConfig } from './antigravity.js';
export { generateCodexConfig } from './codex.js';
export { generateCopilotConfig } from './copilot.js';
export { generateCursorConfig } from './cursor.js';
export { buildContextContent } from './base.js';
export { generateImplementationPlan } from './plan-generator.js';
