import { test, expect } from '@playwright/test';

test('one real shell survives window changes and reload, then stops explicitly', async ({ page }) => {
  test.setTimeout(60_000);
  let launches = 0;
  page.on('websocket', ws => { ws.on('framereceived', frame => { const data = JSON.parse(String(frame.payload)); if (data.type === 'error') console.log('Terminal error:', data.message); }); ws.on('socketerror', error => console.log('Terminal socket:', error)); });
  page.on('request', request => { if (request.url().endsWith('/terminal-test/create')) launches++; });
  await page.addInitScript(() => {
    if (!localStorage.getItem('contextspace_floating_chat_state_v1')) localStorage.setItem('contextspace_floating_chat_state_v1', JSON.stringify({ isOpen: true, openTabs: ['terminal-test'], activeTab: 'terminal-test' }));
  });
  await page.goto('/');
  const pane = page.getByTestId('terminal-pane').filter({ visible: true });
  await pane.getByRole('button', { name: 'Start new session', exact: true }).click();
  await pane.getByRole('combobox', { name: 'CLI harness' }).click();
  await page.getByRole('option', { name: 'Shell', exact: true }).click();
  await pane.getByRole('button', { name: 'Start session', exact: true }).click();
  await expect(pane.getByRole('status')).toHaveText('Running');
  const session = await pane.getByLabel('Terminal sessions').inputValue();
  await expect(pane.getByRole('button', { name: 'Reconnect CLI' })).toHaveCount(0);
  await page.screenshot({ path: 'test-results/terminal-compact.png' });
  await expect(pane.getByRole('button', { name: 'Terminal tools' })).toHaveAttribute('aria-expanded', 'false');
  await pane.getByRole('button', { name: 'Terminal tools' }).click();
  await pane.getByLabel('Screen reader', { exact: true }).check();
  const input = pane.locator('.xterm-helper-textarea');
  const command = process.platform === 'win32' ? "$env:CS_KEEP='42'; Write-Output ('CS_' + 'STARTED')" : 'export CS_KEEP=42; echo CS_STARTED';
  await input.focus(); await page.keyboard.type(command); await page.keyboard.press('Enter');
  await expect(pane.locator('.xterm-accessibility-tree')).toContainText('CS_STARTED');
  const chat = page.getByRole('region', { name: 'CLI Chat', exact: true });
  await chat.getByRole('button', { name: 'Show code' }).click();
  await expect(chat.getByRole('separator', { name: 'Resize code panel' })).toHaveCount(0);
  await expect(pane).toBeHidden();
  await page.screenshot({ path: 'test-results/terminal-compact-inspector.png' });
  await chat.getByRole('button', { name: 'Back to CLI' }).click();
  await expect(pane).toBeVisible();
  await input.focus(); await page.keyboard.type(process.platform === 'win32' ? "Write-Output ('CS_' + $env:CS_KEEP + '_CODE')" : 'echo CS_${CS_KEEP}_CODE'); await page.keyboard.press('Enter');
  await expect(pane.locator('.xterm-accessibility-tree')).toContainText('CS_42_CODE');
  await chat.getByRole('button', { name: 'Documents', exact: true }).click();
  await expect(chat.getByRole('separator', { name: 'Resize documents panel' })).toHaveCount(0);
  await expect(pane).toBeHidden();
  await chat.getByRole('button', { name: 'Back to CLI' }).click();
  await expect(pane).toBeVisible();
  await input.focus(); await page.keyboard.type(process.platform === 'win32' ? "Write-Output ('CS_' + $env:CS_KEEP + '_DOCS')" : 'echo CS_${CS_KEEP}_DOCS'); await page.keyboard.press('Enter');
  await expect(pane.locator('.xterm-accessibility-tree')).toContainText('CS_42_DOCS');
  await page.getByRole('button', { name: 'Maximize floating chat', exact: true }).click();
  const box = await page.getByRole('region', { name: 'CLI Chat', exact: true }).boundingBox();
  expect(box?.width).toBe(page.viewportSize()!.width);
  await chat.getByRole('button', { name: 'Show code' }).click();
  const separator = chat.getByRole('separator', { name: 'Resize code panel' });
  await expect(separator).toHaveAttribute('aria-orientation', 'vertical');
  await separator.focus();
  await page.keyboard.press('ArrowLeft');
  await expect(separator).toHaveAttribute('aria-valuenow', '55');
  await input.focus(); await page.keyboard.type(process.platform === 'win32' ? "Write-Output ('CS_' + $env:CS_KEEP + '_WIDE')" : 'echo CS_${CS_KEEP}_WIDE'); await page.keyboard.press('Enter');
  await expect(pane.locator('.xterm-accessibility-tree')).toContainText('CS_42_WIDE');
  await chat.getByRole('button', { name: 'Hide code' }).click();
  await expect.poll(() => pane.getByLabel('Interactive CLI terminal').evaluate(host => {
    const screen = host.querySelector('.xterm-screen');
    if (!screen) return Infinity;
    return screen.getBoundingClientRect().bottom - host.getBoundingClientRect().bottom;
  })).toBeLessThanOrEqual(1);
  await page.getByRole('button', { name: 'Restore down floating chat' }).click();
  await page.getByRole('button', { name: 'Minimize floating chat' }).click();
  await expect(page.getByTitle('Restore floating CLI chat')).toContainText('CLI running · hidden');
  await page.getByTitle('Restore floating CLI chat').click();
  await chat.getByRole('button', { name: 'Show code' }).click();
  await expect(pane).toBeHidden();
  await page.getByRole('button', { name: 'Add Workspace' }).click();
  await page.getByRole('menuitem').filter({ hasText: 'terminal-other' }).click();
  await expect(pane.getByRole('button', { name: 'Continue a conversation', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'terminal-test', exact: false }).click();
  await expect(chat.getByRole('button', { name: 'Back to CLI' })).toBeVisible();
  await chat.getByRole('button', { name: 'Back to CLI' }).click();
  await expect(pane.getByRole('status')).toHaveText('Running');
  await page.reload();
  await expect(pane.getByRole('status')).toHaveText('Running');
  await expect(pane.getByLabel('Terminal sessions')).toHaveValue(session);
  await expect(pane.getByRole('button', { name: 'Resume session' })).toHaveAttribute('aria-pressed', 'false');
  await expect.poll(() => pane.locator('.xterm-screen').evaluate(screen => screen.getBoundingClientRect().height)).toBeGreaterThan(100);
  await pane.getByRole('button', { name: 'Terminal tools' }).click();
  await pane.getByLabel('Screen reader', { exact: true }).check();
  await input.focus();
  await page.keyboard.type(process.platform === 'win32' ? "Write-Output ('CS_ALIVE_' + $env:CS_KEEP)" : 'echo CS_ALIVE_$CS_KEEP');
  await page.keyboard.press('Enter');
  await expect(pane.locator('.xterm-accessibility-tree')).toContainText('CS_ALIVE_42');
  expect(launches).toBe(1);
  await page.getByRole('button', { name: 'Maximize floating chat', exact: true }).click();
  await page.screenshot({ path: 'test-results/terminal-maximized.png' });
  page.once('dialog', dialog => dialog.accept());
  await pane.getByRole('button', { name: 'End session', exact: true }).click();
  await expect(pane.getByRole('status')).toHaveText('Ended');
  await expect(pane.getByRole('button', { name: 'End session' })).toHaveCount(0);
});

test('a shell that quits on its own is labeled exited', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('contextspace_floating_chat_state_v1', JSON.stringify({ isOpen: true, openTabs: ['terminal-test'], activeTab: 'terminal-test' }));
  });
  await page.goto('/');
  const pane = page.getByTestId('terminal-pane').filter({ visible: true });
  await pane.getByRole('button', { name: 'Start new session', exact: true }).click();
  await pane.getByRole('combobox', { name: 'CLI harness' }).click();
  await page.getByRole('option', { name: 'Shell', exact: true }).click();
  await pane.getByRole('button', { name: 'Start session', exact: true }).click();
  await expect(pane.getByRole('status')).toHaveText('Running');
  await pane.locator('.xterm-helper-textarea').focus();
  await page.keyboard.type('exit 3');
  await page.keyboard.press('Enter');
  await expect(pane.getByRole('status')).toContainText('Exited');
  await expect(pane.getByRole('button', { name: 'End session' })).toHaveCount(0);
});

test('cross-origin terminal creation and websocket attachment are rejected', async ({ request }) => {
  const headers = { Origin: 'https://untrusted.example', 'x-contextspace-terminal': 'bootstrap' };
  expect((await request.post('/api/terminals/bootstrap', { headers })).status()).toBe(403);
  expect((await request.get('/ws/terminal', { headers })).status()).toBe(403);
});
