/**
 * @module core/generation-lock
 * Provenance and drift detection for NexusFlow-generated workspace artifacts.
 *
 * The lock is written last, after a complete generation pass. It therefore
 * describes one immutable input/output snapshot rather than whichever files
 * happened to be written before a partial failure.
 */

import { createHash, randomUUID } from 'node:crypto';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { execa } from 'execa';

import { getGeneratorVersion, getRepoFingerprint } from './analysis-cache.js';
import { loadFeatureConfig, resolveRepoInfos } from './workspace.js';
import { readWorkspaceFile, writeWorkspaceFile } from './storage.js';
import { resolveFeatureRepoPath } from '../utils/feature.js';
import type { RepoInfo } from '../types.js';

export const GENERATION_LOCK_FILE = 'nexusflow.lock';
export const GENERATED_VIEW_HEADER = '<!-- AUTO-GENERATED from AGENTS.md — do not edit -->';
export const GENERATED_SNAPSHOT_HEADER = '<!-- AUTO-GENERATED by NexusFlow from live workspace state — do not edit -->';

const BANNER_START = '<!-- NEXUSFLOW:FRESHNESS:START -->';
const BANNER_END = '<!-- NEXUSFLOW:FRESHNESS:END -->';
const UNCACHEABLE_FINGERPRINT_PREFIX = 'uncacheable:';

export interface GenerationRepoState {
  sha: string;
  fingerprint: string;
}

export interface GenerationSnapshot {
  generatedAt: string;
  toolVersion: string;
  repos: Record<string, GenerationRepoState>;
}

export interface GenerationOutputState {
  hash: string;
  source: string;
  /** Workspace documents use the active storage adapter; resources are local artifacts. */
  location?: 'workspace' | 'local';
}

export interface GenerationLock extends GenerationSnapshot {
  schemaVersion: 1;
  outputs: Record<string, GenerationOutputState>;
}

export interface GenerationDrift {
  kind: 'missing-lock' | 'tool' | 'repo' | 'output';
  name: string;
  generated?: string;
  current?: string;
  message: string;
}

export interface GenerationCheck {
  fresh: boolean;
  lock: GenerationLock | null;
  drift: GenerationDrift[];
}

function assertRelativeOutput(relativePath: string): string {
  const normalized = relativePath.replace(/\\/g, '/');
  if (!normalized || path.isAbsolute(normalized) || normalized.split('/').includes('..')) {
    throw new Error(`Invalid generated output path: ${relativePath}`);
  }
  return normalized;
}

/** Banner text is mutable diagnostic state and is excluded from content hashes. */
export function normalizeGeneratedContent(content: string): string {
  const start = content.indexOf(BANNER_START);
  const end = content.indexOf(BANNER_END);
  if (start < 0 || end < start) return content;
  return `${content.slice(0, start)}${BANNER_START}\n${BANNER_END}${content.slice(end + BANNER_END.length)}`;
}

export function hashGeneratedContent(content: string | Uint8Array): string {
  const retained = typeof content === 'string' ? normalizeGeneratedContent(content) : content;
  return createHash('sha256').update(retained).digest('hex');
}

function inferOutputLocation(relativePath: string): 'workspace' | 'local' {
  const normalized = relativePath.replace(/\\/g, '/');
  return normalized === '.nexusflow/resources.lock.json' ||
    normalized.startsWith('.agents/skills/') ||
    normalized.startsWith('.claude/skills/') ||
    normalized.startsWith('.codex/skills/') ||
    normalized.startsWith('.github/skills/') ||
    normalized.startsWith('.cursor/skills/') ||
    normalized.startsWith('.codex/agents/')
    ? 'local'
    : 'workspace';
}

async function readOutput(
  workspacePath: string,
  featureId: string,
  relativePath: string,
  location: 'workspace' | 'local',
): Promise<string | Uint8Array> {
  return location === 'workspace'
    ? readWorkspaceFile(workspacePath, featureId, relativePath)
    : fs.readFile(path.join(workspacePath, relativePath));
}

export function renderFreshnessBanner(
  snapshot: GenerationSnapshot,
  drift: GenerationDrift[] = [],
): string {
  const repoSummary = Object.entries(snapshot.repos)
    .map(([name, state]) => `${name}@${state.sha.slice(0, 12)}`)
    .join(', ');
  const unverifiable = Object.entries(snapshot.repos)
    .filter(([, state]) => state.fingerprint.startsWith(UNCACHEABLE_FINGERPRINT_PREFIX))
    .map(([name]) => name);
  const lines = drift.length === 0 && unverifiable.length > 0
    ? [
        '> **⚠ NEXUSFLOW CONTEXT FRESHNESS CANNOT BE VERIFIED.**',
        `> Regenerated from ${unverifiable.join(', ')} with uncommitted files that cannot be safely fingerprinted on this platform.`,
        '> Treat generated facts as provisional; commit the files or verify live state with `nexusflow status`.',
      ]
    : drift.length === 0
    ? [
        '> **NexusFlow snapshot:** ' + (repoSummary || 'no repositories') + `. Verify live state with \`nexusflow refresh --check\`.`,
      ]
    : [
        '> **⚠ STALE NEXUSFLOW CONTEXT — GENERATED FACTS MAY BE WRONG.**',
        ...drift.map((item) => `> ${item.message}`),
        '> Run `nexusflow refresh` before relying on generated facts.',
      ];
  return [BANNER_START, ...lines, BANNER_END].join('\n');
}

export async function captureGenerationSnapshot(repos: RepoInfo[]): Promise<GenerationSnapshot> {
  const states = await Promise.all(repos.map(async (repo) => {
    const [{ stdout }, fingerprint] = await Promise.all([
      execa('git', ['rev-parse', 'HEAD'], { cwd: repo.path }),
      getRepoFingerprint(repo.path),
    ]);
    // A null fingerprint means cache reuse is unsafe, not that generation is
    // impossible. Preserve the generated output with an explicit unverifiable
    // snapshot that always trips the next freshness check.
    const recordedFingerprint = fingerprint ?? `${UNCACHEABLE_FINGERPRINT_PREFIX}${randomUUID()}`;
    return [repo.name, { sha: stdout.trim(), fingerprint: recordedFingerprint }] as const;
  }));

  return {
    generatedAt: new Date().toISOString(),
    toolVersion: getGeneratorVersion(),
    repos: Object.fromEntries(states),
  };
}

export async function writeGenerationLock(
  workspacePath: string,
  snapshot: GenerationSnapshot,
  outputs: Array<{ path: string; source: string; location?: 'workspace' | 'local' }>,
): Promise<GenerationLock> {
  const feature = await loadFeatureConfig(workspacePath);
  const featureId = feature?.id ?? path.basename(workspacePath);
  const outputEntries = await Promise.all(outputs.map(async (output) => {
    const relativePath = assertRelativeOutput(output.path);
    const location = output.location ?? inferOutputLocation(relativePath);
    const content = await readOutput(workspacePath, featureId, relativePath, location);
    return [relativePath, { hash: hashGeneratedContent(content), source: output.source, location }] as const;
  }));
  const outputState = Object.fromEntries(outputEntries);
  const previous = await readGenerationLock(workspacePath);
  const unchanged = previous?.toolVersion === snapshot.toolVersion &&
    JSON.stringify(previous.repos) === JSON.stringify(snapshot.repos) &&
    JSON.stringify(previous.outputs) === JSON.stringify(outputState);
  const lock: GenerationLock = {
    schemaVersion: 1,
    ...snapshot,
    generatedAt: unchanged ? previous.generatedAt : snapshot.generatedAt,
    outputs: outputState,
  };
  const target = path.join(workspacePath, GENERATION_LOCK_FILE);
  const temp = `${target}.tmp-${process.pid}-${randomUUID()}`;
  await fs.writeFile(temp, JSON.stringify(lock, null, 2) + '\n', 'utf-8');
  await fs.rename(temp, target);
  return lock;
}

export async function readGenerationLock(workspacePath: string): Promise<GenerationLock | null> {
  try {
    const parsed = JSON.parse(await fs.readFile(path.join(workspacePath, GENERATION_LOCK_FILE), 'utf-8')) as GenerationLock;
    if (parsed.schemaVersion !== 1 || !parsed.repos || !parsed.outputs) return null;
    return parsed;
  } catch {
    return null;
  }
}

async function currentWorkspaceRepos(workspacePath: string): Promise<RepoInfo[]> {
  const feature = await loadFeatureConfig(workspacePath);
  if (!feature) throw new Error(`Workspace manifest not found at ${workspacePath}.`);
  return resolveRepoInfos(feature.repos.map((repo) => resolveFeatureRepoPath(feature, workspacePath, repo)));
}

export async function checkGenerationLock(
  workspacePath: string,
  options: { markDocuments?: boolean } = {},
): Promise<GenerationCheck> {
  const lock = await readGenerationLock(workspacePath);
  if (!lock) {
    return {
      fresh: false,
      lock: null,
      drift: [{ kind: 'missing-lock', name: GENERATION_LOCK_FILE, message: 'nexusflow.lock is missing or invalid.' }],
    };
  }

  const drift: GenerationDrift[] = [];
  const currentToolVersion = getGeneratorVersion();
  if (lock.toolVersion !== currentToolVersion) {
    drift.push({
      kind: 'tool',
      name: 'NexusFlow',
      generated: lock.toolVersion,
      current: currentToolVersion,
      message: `Generated with NexusFlow ${lock.toolVersion}; current tool is ${currentToolVersion}.`,
    });
  }
  const repos = await currentWorkspaceRepos(workspacePath);
  const repoDrift = await Promise.all(repos.map(async (repo): Promise<GenerationDrift | null> => {
    const recorded = lock.repos[repo.name];
    const current = await getRepoFingerprint(repo.path);
    if (!recorded || !current || recorded.fingerprint !== current) {
      const sha = await execa('git', ['rev-parse', 'HEAD'], { cwd: repo.path })
        .then((result) => result.stdout.trim())
        .catch(() => 'unavailable');
      const wasUncacheable = recorded?.fingerprint.startsWith(UNCACHEABLE_FINGERPRINT_PREFIX);
      return {
        kind: 'repo',
        name: repo.name,
        generated: recorded?.sha,
        current: sha,
        message: wasUncacheable
          ? `Generated from ${repo.name}@${recorded?.sha.slice(0, 12) ?? 'unknown'} while dirty-file freshness could not be safely verified on this platform.`
          : `Generated at ${repo.name}@${recorded?.sha.slice(0, 12) ?? 'unknown'}; repo now at ${sha.slice(0, 12)}${current?.includes('+') ? ' with uncommitted changes' : ''}.`,
      };
    }
    return null;
  }));
  drift.push(...repoDrift.filter((item): item is GenerationDrift => item !== null));

  const feature = await loadFeatureConfig(workspacePath);
  const featureId = feature?.id ?? path.basename(workspacePath);
  const outputDrift = await Promise.all(Object.entries(lock.outputs).map(async ([relativePath, output]): Promise<GenerationDrift | null> => {
    try {
      const safePath = assertRelativeOutput(relativePath);
      const location = output.location ?? inferOutputLocation(safePath);
      const content = await readOutput(workspacePath, featureId, safePath, location);
      const current = hashGeneratedContent(content);
      if (current !== output.hash) {
        return { kind: 'output', name: relativePath, generated: output.hash, current, message: `Generated view ${relativePath} has drifted from its recorded hash.` };
      }
    } catch {
      return { kind: 'output', name: relativePath, generated: output.hash, message: `Generated view ${relativePath} is missing.` };
    }
    return null;
  }));
  drift.push(...outputDrift.filter((item): item is GenerationDrift => item !== null));

  if (options.markDocuments && drift.some((item) => item.kind === 'repo' || item.kind === 'tool')) {
    await markFreshnessBanners(workspacePath, lock, drift);
  }
  return { fresh: drift.length === 0, lock, drift };
}

async function markFreshnessBanners(
  workspacePath: string,
  snapshot: GenerationSnapshot,
  drift: GenerationDrift[],
): Promise<void> {
  const banner = renderFreshnessBanner(snapshot, drift.filter((item) => item.kind === 'repo' || item.kind === 'tool'));
  const feature = await loadFeatureConfig(workspacePath);
  const featureId = feature?.id ?? path.basename(workspacePath);
  for (const [relativePath, output] of Object.entries((snapshot as GenerationLock).outputs ?? {})) {
    const safePath = assertRelativeOutput(relativePath);
    const location = output.location ?? inferOutputLocation(safePath);
    try {
      const raw = await readOutput(workspacePath, featureId, safePath, location);
      if (typeof raw !== 'string') continue;
      const content = raw;
      const start = content.indexOf(BANNER_START);
      const end = content.indexOf(BANNER_END);
      if (start < 0 || end < start) continue;
      const updated = `${content.slice(0, start)}${banner}${content.slice(end + BANNER_END.length)}`;
      if (location === 'workspace') await writeWorkspaceFile(workspacePath, featureId, safePath, updated);
      else await fs.writeFile(path.join(workspacePath, safePath), updated, 'utf-8');
    } catch {
      // Missing files are already reported as output drift.
    }
  }
}
