/** Workspace-local access to the installed CLI, including desktop's bundled runtime. */
import * as fs from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse, stringify, type TomlTable } from 'smol-toml';
import type { AIAssistant } from '../types.js';
import { BRAND_CONFIG } from './constants.js';
import { assertNoLinkedPathComponents, atomicWriteFile } from '../resources/fs-safety.js';
import { mcpTargetsFor } from '../harness/manifest.js';

const CURSOR_MCP_CONFIG = '.cursor/mcp.json';

export const CLI_LAUNCHER = '.contextspace/bin/ctxspace';
export const CLI_ALIAS_LAUNCHER = '.contextspace/bin/contextspace';
export const LAUNCHER_MARKER = 'Generated by ContextSpace: workspace CLI';
export interface CliRuntime { command: string; entry: string; electron?: boolean }

export function currentCliRuntime(): CliRuntime {
  return { command: process.execPath, entry: fileURLToPath(new URL('../index.js', import.meta.url)), electron: Boolean(process.versions.electron) };
}

/** Absolute path of the generated launcher; on Windows only the `.cmd` variant is executable. */
export function launcherCommandPath(root: string, platform = process.platform): string {
  return path.join(root, platform === 'win32' ? `${CLI_LAUNCHER}.cmd` : CLI_LAUNCHER);
}

/**
 * The generated launcher for `root`, but only when it is one of ours.
 *
 * A user may replace the launcher with their own script, so the marker check is
 * what makes it safe to point a generated MCP config at it. The SDK harnesses
 * use this instead of embedding their own runtime paths, which for a desktop
 * install are the same ephemeral `/tmp` paths this module exists to avoid.
 */
export function generatedLauncher(root: string, platform = process.platform): string | undefined {
  const launcher = launcherCommandPath(root, platform);
  try {
    return readFileSync(launcher, 'utf8').includes(LAUNCHER_MARKER) ? launcher : undefined;
  } catch {
    return undefined;
  }
}

export async function generateWorkspaceTools(root: string, assistants: AIAssistant[], runtime = currentCliRuntime()): Promise<string[]> {
  const outputs: string[] = [];
  const marker = LAUNCHER_MARKER;
  const write = async (relative: string, content: string) => {
    const target = path.join(root, relative);
    await assertNoLinkedPathComponents(root, target);
    await fs.mkdir(path.dirname(target), { recursive: true });
    let existing: string | undefined;
    try { existing = await fs.readFile(target, 'utf8'); }
    catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    if (existing !== content) await atomicWriteFile(target, content);
    outputs.push(relative);
  };
  const shellQuote = (value: string) => `'${value.replaceAll("'", "'\\''")}'`;
  const cmdQuote = (value: string) => {
    if (/["\r\n]/.test(value)) throw new Error('The CLI runtime path cannot be represented in a Windows launcher.');
    return `"${value.replaceAll('%', '%%')}"`;
  };
  /**
   * A desktop launcher must resolve its runtime at call time.
   *
   * An AppImage install runs from `/tmp/appimage_extracted_<md5>`, and both the
   * host binary and the backend entry live there. That directory is temporary in
   * three separate ways: it is cleared on reboot, its name changes with every
   * app update, and an in-place update rewrites its contents while workspaces
   * still point at it. Recording those paths is what made generated launchers
   * and MCP configs break silently. The AppImage itself is not a usable
   * substitute: it ignores `ELECTRON_RUN_AS_NODE` and would open the desktop
   * GUI instead of running a command.
   *
   * So the recorded paths are only a fast path. When either is gone the newest
   * extraction is used, and when the app has never run the launcher says what to
   * do rather than failing with a bare "no such file or directory".
   *
   * AppImage is a Linux format, so only the POSIX launcher needs this; the
   * Windows launcher keeps the recorded paths.
   */
  const selfResolvingRuntime = [
    `bin=${shellQuote(runtime.command.replaceAll('\\', '/'))}`,
    `entry=${shellQuote(runtime.entry.replaceAll('\\', '/'))}`,
    'if [ ! -x "$bin" ] || [ ! -f "$entry" ]; then',
    '  dir=$(ls -dt "${TMPDIR:-/tmp}"/appimage_extracted_* 2>/dev/null | head -1)',
    '  if [ -n "$dir" ]; then bin="$dir/contextspace-desktop"; entry="$dir/resources/backend/dist/index.js"; fi',
    'fi',
    'if [ ! -x "$bin" ] || [ ! -f "$entry" ]; then',
    '  echo "ContextSpace: the desktop runtime is unavailable (no AppImage extraction under ${TMPDIR:-/tmp})." >&2',
    '  echo "Launch the ContextSpace desktop app once, then retry." >&2',
    '  exit 1',
    'fi',
  ].join('\n');
  const shellLauncher = runtime.electron
    ? `#!/bin/sh\n# ${marker}\nexport ELECTRON_RUN_AS_NODE=1\n${selfResolvingRuntime}\nexec "$bin" "$entry" "$@"\n`
    : `#!/bin/sh\n# ${marker}\nexec ${shellQuote(runtime.command.replaceAll('\\', '/'))} ${shellQuote(runtime.entry.replaceAll('\\', '/'))} "$@"\n`;
  const cmdLauncher = `@echo off\r\nrem ${marker}\r\nsetlocal DisableDelayedExpansion\r\n${runtime.electron ? 'set "ELECTRON_RUN_AS_NODE=1"\r\n' : ''}${cmdQuote(runtime.command)} ${cmdQuote(runtime.entry)} %*\r\nexit /b %errorlevel%\r\n`;
  const launchers = [
    [CLI_LAUNCHER, shellLauncher],
    [`${CLI_LAUNCHER}.cmd`, cmdLauncher],
    [CLI_ALIAS_LAUNCHER, shellLauncher],
    [`${CLI_ALIAS_LAUNCHER}.cmd`, cmdLauncher],
  ];
  for (const [relative, content] of launchers) {
    await assertNoLinkedPathComponents(root, path.join(root, relative));
    try {
      if (!(await fs.readFile(path.join(root, relative), 'utf8')).includes(marker)) throw new Error(`Refusing to overwrite a custom launcher: ${relative}`);
    } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    await write(relative, content);
  }
  await fs.chmod(path.join(root, CLI_LAUNCHER), 0o755);
  await fs.chmod(path.join(root, CLI_ALIAS_LAUNCHER), 0o755);

  const server = { command: launcherCommandPath(root), args: ['mcp', 'run', root, '--role', 'interactive'] };
  // Which MCP configs to write comes from the harness manifest. Antigravity
  // declares none because it reads a user-level config, and writing that on
  // refresh would be a side effect outside the workspace.
  const targets = mcpTargetsFor(assistants);
  const configs = targets.filter((target) => target.format === 'json');
  for (const target of configs) {
    await assertNoLinkedPathComponents(root, path.join(root, target.path));
    let config: Record<string, any> = {};
    try { config = JSON.parse(await fs.readFile(path.join(root, target.path), 'utf8')); }
    catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    if (!config || Array.isArray(config) || typeof config !== 'object' || (config[target.key] && (Array.isArray(config[target.key]) || typeof config[target.key] !== 'object'))) throw new Error(`Invalid MCP configuration: ${target.path}`);
    config[target.key] = { ...config[target.key], [BRAND_CONFIG.mcp.serverName]: { ...(target.entryType ? { type: target.entryType } : {}), ...server } };
    await write(target.path, JSON.stringify(config, null, 2) + '\n');
  }
  // Remove only the exact Cursor server emitted unconditionally by older versions.
  // Leave custom entries and other servers alone when Cursor is not selected.
  if (!targets.some((target) => target.path === CURSOR_MCP_CONFIG)) {
    const target = path.join(root, '.cursor/mcp.json');
    await assertNoLinkedPathComponents(root, target);
    let old: Record<string, any> | undefined;
    try { old = JSON.parse(await fs.readFile(target, 'utf8')); }
    catch (error) { if (!(error instanceof SyntaxError) && (error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    const prior = old?.mcpServers?.[BRAND_CONFIG.mcp.serverName];
    if (prior?.command === 'npx' && Object.keys(prior).length === 2 &&
        JSON.stringify(prior.args) === JSON.stringify(['-y', BRAND_CONFIG.mcp.packageName, 'mcp', 'run'])) {
      delete old!.mcpServers[BRAND_CONFIG.mcp.serverName];
      if (Object.keys(old!.mcpServers).length === 0) delete old!.mcpServers;
      if (Object.keys(old!).length === 0) await fs.unlink(target);
      else await atomicWriteFile(target, JSON.stringify(old, null, 2) + '\n');
    }
  }
  for (const target of targets.filter((candidate) => candidate.format === 'toml')) {
    await assertNoLinkedPathComponents(root, path.join(root, target.path));
    let config: TomlTable = {};
    try { config = parse(await fs.readFile(path.join(root, target.path), 'utf8')); }
    catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    const existing = config[target.key];
    if (existing && (typeof existing !== 'object' || Array.isArray(existing))) throw new Error(`Invalid ${target.key} table in ${target.path}.`);
    config[target.key] = { ...(existing as Record<string, any>), [BRAND_CONFIG.mcp.serverName]: server };
    await write(target.path, stringify(config));
  }
  return outputs;
}
