/** Workspace-local access to the installed CLI, including desktop's bundled runtime. */
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse, stringify, type TomlTable } from 'smol-toml';
import type { AIAssistant } from '../types.js';
import { BRAND_CONFIG } from './constants.js';
import { assertNoLinkedPathComponents, atomicWriteFile } from '../resources/fs-safety.js';

export const CLI_LAUNCHER = '.contextspace/bin/ctxspace';
export interface CliRuntime { command: string; entry: string; electron?: boolean }
export function currentCliRuntime(): CliRuntime {
  return { command: process.execPath, entry: fileURLToPath(new URL('../index.js', import.meta.url)), electron: Boolean(process.versions.electron) };
}

export async function generateWorkspaceTools(root: string, assistants: AIAssistant[], runtime = currentCliRuntime()): Promise<string[]> {
  const outputs: string[] = [];
  const marker = 'Generated by ContextSpace: workspace CLI';
  const write = async (relative: string, content: string) => {
    const target = path.join(root, relative);
    await assertNoLinkedPathComponents(root, target);
    await fs.mkdir(path.dirname(target), { recursive: true });
    let existing: string | undefined;
    try { existing = await fs.readFile(target, 'utf8'); }
    catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    if (existing !== content) await atomicWriteFile(target, content);
    outputs.push(relative);
  };
  const shellQuote = (value: string) => `'${value.replaceAll("'", "'\\''")}'`;
  const cmdQuote = (value: string) => {
    if (/["\r\n]/.test(value)) throw new Error('The CLI runtime path cannot be represented in a Windows launcher.');
    return `"${value.replaceAll('%', '%%')}"`;
  };
  const launchers = [
    [CLI_LAUNCHER, `#!/bin/sh\n# ${marker}\n${runtime.electron ? 'export ELECTRON_RUN_AS_NODE=1\n' : ''}exec ${shellQuote(runtime.command.replaceAll('\\', '/'))} ${shellQuote(runtime.entry.replaceAll('\\', '/'))} "$@"\n`],
    [`${CLI_LAUNCHER}.cmd`, `@echo off\r\nrem ${marker}\r\nsetlocal DisableDelayedExpansion\r\n${runtime.electron ? 'set "ELECTRON_RUN_AS_NODE=1"\r\n' : ''}${cmdQuote(runtime.command)} ${cmdQuote(runtime.entry)} %*\r\nexit /b %errorlevel%\r\n`],
  ];
  for (const [relative, content] of launchers) {
    await assertNoLinkedPathComponents(root, path.join(root, relative));
    try {
      if (!(await fs.readFile(path.join(root, relative), 'utf8')).includes(marker)) throw new Error(`Refusing to overwrite a custom launcher: ${relative}`);
    } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    await write(relative, content);
  }
  await fs.chmod(path.join(root, CLI_LAUNCHER), 0o755);

  const server = { command: runtime.command, args: [runtime.entry, 'mcp', 'run', root, '--role', 'interactive'],
    ...(runtime.electron ? { env: { ELECTRON_RUN_AS_NODE: '1' } } : {}) };
  const configs: Array<[string, string]> = [];
  if (assistants.includes('claude') || assistants.includes('copilot')) configs.push(['.mcp.json', 'mcpServers']);
  if (assistants.includes('cursor')) configs.push(['.cursor/mcp.json', 'mcpServers']);
  if (assistants.includes('copilot')) configs.push(['.vscode/mcp.json', 'servers']);
  // Antigravity uses a user-level MCP configuration. Do not write its global config on refresh.
  for (const [relative, key] of configs) {
    await assertNoLinkedPathComponents(root, path.join(root, relative));
    let config: Record<string, any> = {};
    try { config = JSON.parse(await fs.readFile(path.join(root, relative), 'utf8')); }
    catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    if (!config || Array.isArray(config) || typeof config !== 'object' || (config[key] && (Array.isArray(config[key]) || typeof config[key] !== 'object'))) throw new Error(`Invalid MCP configuration: ${relative}`);
    config[key] = { ...config[key], [BRAND_CONFIG.mcp.serverName]: { ...(key === 'servers' ? { type: 'stdio' } : {}), ...server } };
    await write(relative, JSON.stringify(config, null, 2) + '\n');
  }
  // Remove only the exact Cursor server emitted unconditionally by older versions.
  // Leave custom entries and other servers alone when Cursor is not selected.
  if (!assistants.includes('cursor')) {
    const target = path.join(root, '.cursor/mcp.json');
    await assertNoLinkedPathComponents(root, target);
    let old: Record<string, any> | undefined;
    try { old = JSON.parse(await fs.readFile(target, 'utf8')); }
    catch (error) { if (!(error instanceof SyntaxError) && (error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    const prior = old?.mcpServers?.[BRAND_CONFIG.mcp.serverName];
    if (prior?.command === 'npx' && Object.keys(prior).length === 2 &&
        JSON.stringify(prior.args) === JSON.stringify(['-y', BRAND_CONFIG.mcp.packageName, 'mcp', 'run'])) {
      delete old!.mcpServers[BRAND_CONFIG.mcp.serverName];
      if (Object.keys(old!.mcpServers).length === 0) delete old!.mcpServers;
      if (Object.keys(old!).length === 0) await fs.unlink(target);
      else await atomicWriteFile(target, JSON.stringify(old, null, 2) + '\n');
    }
  }
  if (assistants.includes('codex')) {
    const relative = '.codex/config.toml';
    await assertNoLinkedPathComponents(root, path.join(root, relative));
    let config: TomlTable = {};
    try { config = parse(await fs.readFile(path.join(root, relative), 'utf8')); }
    catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
    const existing = config.mcp_servers;
    if (existing && (typeof existing !== 'object' || Array.isArray(existing))) throw new Error('Invalid Codex mcp_servers table.');
    config.mcp_servers = { ...(existing as Record<string, any>), [BRAND_CONFIG.mcp.serverName]: server };
    await write(relative, stringify(config));
  }
  return outputs;
}
